codecov:
  require_ci_to_pass: yes

coverage:
  range: 60..90
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        flags:
          - server
    patch:
      default:
        target: 85%
        threshold: 0%
        only_pulls: true
        if_ci_failed: ignore
        flags:
          - server

comment:
  layout: "diff, flags"
  require_changes: true
  show_critical_paths: true

flags:
  server:
    paths:
      - "**/*.py"
    carryforward: true
  ui-tests:
    paths:
      - "**/*.js"
    carryforward: true
  server-ui:
    paths:
      - "**/*.py"
    carryforward: true

profiling:
   critical_files_paths:
      - /itds/api.py
      - /itds/app.py
      - /itds/auth.py
      - /itds/boot.py
      - /itds/client.py
      - /itds/handler.py
      - /itds/migrate.py
      - /itds/sessions.py
      - /itds/utils/*
      - /itds/desk/reportview.py
      - /itds/desk/form/*
      - /itds/model/*
      - /itds/core/doctype/doctype/*
      - /itds/core/doctype/data_import/*
      - /itds/core/doctype/user/*
      - /itds/core/doctype/user/*
      - /itds/query_builder/*
      - /itds/database/*
